#!/usr/bin/env bash

if [[ "$1" == "-h" ]]; then
	echo "Usage: ./atker [protocol] [profile]"
	echo "Available protocols: HTTP, TCP, UDP, ICMP"
	echo "Available profiles: "
	echo "	- #1: 100 packets/s, 0B payload (-i u10000)"
	echo "	- #2: 200 packets/s, 0B payload (-i u5000)"
	echo "	- #3: 100 packets/s, small payload (-i u10000 -d X)"
	echo "		+ TCP: 26 bytes"
	echo "		+ UDP: 50 bytes"
	echo "		+ ICMP: 48 bytes"
	echo "	- #4: 100 packets/s, 1KB payload (-i u10000 -d 1000)"
else
	PROTOCOL=$(echo "$1" | tr '[:upper:]' '[:lower:]')
	date >> time.txt
	echo -n "Attacker sending $PROTOCOL packets with profile #$2 - "
	SERVER="192.168.56.103"
	SPEED="0"
	LOAD="0"
	FLAG=""
	PORT=""
	MODE=""
	
	case "$2" in
		1)
			SPEED="u10000"
			echo "100 packets/s"

			;;
		2)
			SPEED="u5000"
			echo "200 packets/s"
			;;
		3)
			SPEED="u10000"
			case $PROTOCOL in
				tcp)
					LOAD="26"
					;;
				udp)
					LOAD="50"
					;;
				icmp)
					
					LOAD="48"
					;;
				*)
					;;
			esac
			echo "100 packets/s, ${LOAD}B payload"
			;;
		4)
			SPEED="u10000"
			LOAD="1000"
			echo "100 packets/s, 1KB payload"
			;;
		*)
			if [[ $1 != http ]]; then
				echo "Invalid profile: Available profiles: 1, 2, 3, 4. View \"-h\" for more details."
				echo "Exiting..."
			else
				echo ""
			fi
			;;
	esac

	case $PROTOCOL in
		tcp | udp | icmp)
			case $PROTOCOL in
				tcp)
					FLAG="-S" # --syn
					PORT="-p 80"
					;;
				udp)
					PORT="-p 80"
					MODE="-2" # --udp
					;;
				icmp)
					MODE="-1" # --icmp
					;;
			esac
			sudo timeout 45s hping3 $MODE -i $SPEED -d $LOAD $FLAG $PORT $SERVER
			;;
		http)
			sudo timeout 45s bash -c "while true; do curl $SERVER; done"
			;;
		*)
			echo
			echo "Invalid protocol. Available protocols: HTTP, TCP, UDP, ICMP"
			echo "Exiting..."
			;;
	esac
fi
